### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by idelidelidel** [celenny/card-html-css#1]
Os links do Instagram e do Twitter estão levando ao erro 404, como exemplificado a seguir:

![image](https://user-images.githubusercontent.com/87836742/165952650-e2aa04f0-31da-4543-bf04-69cf832eccd6.png)

**Comment by celenny** [comment]
Valeu pela issue @idelidelidel , nem tinha percebido que os links estavam quebrados. Acebei de corrigir o erro 💜
